### ISSUE TITLE
Rust Crate

### ISSUE THREAD

**Issue by trippjoe** [b1tg/pickup#2]
Hello, I found this repo on [reddit](https://www.reddit.com/r/rust/comments/lhdvpt/announcing_pickup_copy_files_to_clipboard_from/) when searching for a cross platform solution to copy files to the users clipboard. I appreciate the work you have done and would like to create a rust crate from the functions you've created. In addition to creating a crate I intend on implementing support for Linux as well. You have not specified a license for this repo, therefore I am seeking your approval prior to following through with my intentions.

**Comment by b1tg** [comment]
MIT license added now, feel free to make improvements you want.
